# Haven't updated to lua :(

# Mod Key:
$mod = SUPER

# Monitors:
monitor = eDP-1, 1920x1280@60, 0x0, 1, transform, 0
monitor = DP-1, 3840x2160, auto, 1, transform, 0

# Auto-Start:
exec-once = alacritty
exec-once = hyprpaper
exec-once = waybar
exec-once = quickshell # My Moon App launcher widget 
exec-once = quickshell -p ~/.config/quickshell/EasterEgg.qml

# Binds:
bind = $mod, Return, exec, alacritty
bind = $mod, Escape, exit
bind = $mod, BACKSPACE, killactive
bind = $mod SHIFT, Tab, fullscreen
bind = $mod, Tab, togglefloating
bind = , PRINT, exec, hyprshot -m region

# Window management:
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Moon app launcher and Wofi:
bind = $mod, Space, exec, ~/.config/quickshell/scripts/WidgetOverlay.sh
bind = $mod SHIFT, Space, exec, killall wofi || wofi --show drun

# Volume and brightness:
bind = , XF86AudioRaiseVolume, exec, pamixer -i 10 
bind = , XF86AudioLowerVolume, exec, pamixer -d 10
bind = , XF86AudioMute, exec, pamixer --set-volume 0
bind = , XF86MonBrightnessUp, exec, brightnessctl set 10%+
bind = , XF86MonBrightnessDown, exec, brightnessctl set 10%-

# Workspaces
bind = $mod, Left, workspace, -1
bind = $mod, Right, exec, ~/.config/hypr/scripts/MaxWorkspaces.sh # (Small script for limiting the number of workspaces to 10)
bind = $mod SHIFT, Left, movetoworkspace, -1
bind = $mod SHIFT, Right, exec, ~/.config/hypr/scripts/MoveMaxWorkspaces.sh

# Customization:
decoration {
	blur {
		enabled = false
	}
	shadow {
		enabled = false
	}
	rounding = 15
}

general {
	border_size = 1
	col.inactive_border = rgba(00000000)
	col.active_border = rgba(787878ff)
}

# Input:
input {
    kb_layout = us

    touchpad {
        natural_scroll = true
        tap-to-click = true
	middle_button_emulation = true
	disable_while_typing = true # Can be changed if necesary
    }
}

# Environment
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

